#!/usr/bin/env bash
# Refresh the `plugin` branch so it matches `main` minus test infrastructure.
#
# The `plugin` branch is what the Godot Asset Library consumes. It contains
# the addon under addons/gltf_pipeline/ but drops test runners, GUT, fixtures,
# project.godot, and other repo-development artifacts that shouldn't ship to
# end users.
#
# Model: this script does NOT preserve plugin's prior history. It resets
# plugin to main's tip, removes the excluded paths, commits the result as a
# single "strip" commit, and force-pushes. AssetLib consumers don't care about
# plugin's internal commit history — they care that the tree matches the
# current addon. If you need preserved history, cherry-pick manually instead.
#
# Usage:
#   scripts/refresh-plugin-branch.sh --dry-run     # show what would happen
#   scripts/refresh-plugin-branch.sh                # apply locally, do NOT push
#   scripts/refresh-plugin-branch.sh --push         # apply AND force-push
#
# Safety:
#   - Refuses to run with a dirty working tree.
#   - Fetches origin before any work.
#   - Restores your original branch on exit (success or failure).
#   - Uses --force-with-lease, not --force: refuses to clobber a remote plugin
#     that has diverged from what this script last saw.

set -euo pipefail

# ---- Config -------------------------------------------------------------
REMOTE="origin"
SOURCE_BRANCH="main"
TARGET_BRANCH="plugin"

# Paths removed from the plugin branch. Keep in sync with what the
# AssetLib distribution should NOT contain. Derived once from
# `git diff origin/plugin..origin/main --stat` — update if main grows new
# development-only top-level paths.
EXCLUDE_PATHS=(
  ".gutconfig.json"
  "icon.svg"
  "project.godot"
  "run_tests.sh"
  "scripts"
  "test"
  "addons/gut"
)

# ---- Args ---------------------------------------------------------------
DRY_RUN=0
DO_PUSH=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --push) DO_PUSH=1 ;;
    -h|--help)
      sed -n '2,28p' "$0"
      exit 0
      ;;
    *) echo "unknown arg: $arg" >&2; exit 2 ;;
  esac
done

# ---- Preconditions ------------------------------------------------------
# Dry-run is read-only (no checkout, no reset), so it skips the clean-tree
# guard. The apply path enforces it because `git reset --hard` would otherwise
# wipe uncommitted work.
if [[ $DRY_RUN -eq 0 && -n "$(git status --porcelain)" ]]; then
  echo "error: working tree not clean. commit or stash first." >&2
  exit 1
fi

ORIGINAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
if [[ "$ORIGINAL_BRANCH" == "HEAD" ]]; then
  echo "error: detached HEAD. check out a branch first." >&2
  exit 1
fi

restore() {
  local status=$?
  if [[ "$(git rev-parse --abbrev-ref HEAD)" != "$ORIGINAL_BRANCH" ]]; then
    echo "restoring $ORIGINAL_BRANCH..."
    git checkout --quiet "$ORIGINAL_BRANCH" || true
  fi
  exit $status
}
trap restore EXIT

# ---- Fetch --------------------------------------------------------------
echo "fetching $REMOTE..."
git fetch --quiet "$REMOTE"

# ---- Dry run ------------------------------------------------------------
if [[ $DRY_RUN -eq 1 ]]; then
  echo
  echo "would reset $TARGET_BRANCH to $REMOTE/$SOURCE_BRANCH ($(git rev-parse --short "$REMOTE/$SOURCE_BRANCH"))"
  echo "would remove these paths from the resulting tree:"
  for p in "${EXCLUDE_PATHS[@]}"; do
    if git cat-file -e "$REMOTE/$SOURCE_BRANCH:$p" 2>/dev/null; then
      echo "  - $p"
    else
      echo "  - $p  (not present on $REMOTE/$SOURCE_BRANCH — will be skipped)"
    fi
  done
  echo
  if [[ $DO_PUSH -eq 1 ]]; then
    echo "would then force-push (with --force-with-lease) to $REMOTE/$TARGET_BRANCH"
  else
    echo "would NOT push (pass --push to publish)"
  fi
  exit 0
fi

# ---- Apply --------------------------------------------------------------
echo "checking out $TARGET_BRANCH..."
if git show-ref --verify --quiet "refs/heads/$TARGET_BRANCH"; then
  git checkout --quiet "$TARGET_BRANCH"
else
  git checkout --quiet -b "$TARGET_BRANCH" "$REMOTE/$TARGET_BRANCH"
fi

echo "resetting to $REMOTE/$SOURCE_BRANCH..."
git reset --hard --quiet "$REMOTE/$SOURCE_BRANCH"

echo "removing excluded paths..."
for p in "${EXCLUDE_PATHS[@]}"; do
  if [[ -e "$p" ]]; then
    git rm -rq "$p"
  fi
done

echo "committing strip..."
git commit --quiet -m "strip test infrastructure for Asset Library distribution

Regenerated by scripts/refresh-plugin-branch.sh. Removes paths that
shouldn't reach AssetLib consumers: GUT, test suites, project files,
repo tooling. The addon itself under addons/gltf_pipeline/ matches
$REMOTE/$SOURCE_BRANCH exactly."

# ---- Push ---------------------------------------------------------------
if [[ $DO_PUSH -eq 1 ]]; then
  echo "force-pushing with lease..."
  git push --force-with-lease "$REMOTE" "$TARGET_BRANCH"
  echo "done. $REMOTE/$TARGET_BRANCH refreshed."
else
  echo
  echo "local $TARGET_BRANCH updated but NOT pushed."
  echo "inspect with: git log $TARGET_BRANCH --oneline -n 3"
  echo "push when ready: git push --force-with-lease $REMOTE $TARGET_BRANCH"
fi
